# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab0ec8c91b25f49a106514dc07515e39c6a828607013bdda674e2a09681c634bfcb3d17849266fae9419db4e7fabe4255e85176a19c45aee1eca8218c546800

test:
  secret_key_base: 50ebe40e17a172fee3758e7536de0713c83815ba34325fed2ed8a07d3523dd9fc2a66594234095c5a7df9d284f28218330a120816c7b7a5b618a29902c2ed0d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
